GET http://localhost:8081/api/shop?lng=-57.5&lat=-25.3&from=0&quantity=10
Cache-Control: no-cache
Content-Type: application/jso
//http://192.168.43.214:8081/api/shop?lng=-57.5&lat=25.3&from=0&quantity=10

###
GET http://localhost:8081/api/shop/all?from=0&quantity=10
Cache-Control: no-cache
Content-Type: application/json
###

GET http://localhost:8081/api/shop/all
Cache-Control: no-cache
Content-Type: application/json
###
GET http://localhost:8081/api/shop/1
Cache-Control: no-cache
Content-Type: application/json

###
GET http://localhost:8081/api/shop/1/stock?from=0&quantity=10
Cache-Control: no-cache
###
###
GET http://localhost:8081/api/shop/search?lng=5.0&lat=5.0&tab=CLOTHES&searchText=MAGAS&from=0&quantity=10
Cache-Control: no-cache

###
GET http://localhost:8081/api/shop/search?tab=FOOD&searchText=MAGAS&from=0&quantity=10
Cache-Control: no-cache
###

GET http://localhost:8081/api/stock/1
Cache-Control: no-cache

###
GET http://localhost:8081/api/stock/search?searchValue=2 3 &from=0&quantity=10
Cache-Control: no-cache
Content-Type: application/json
###
GET http://localhost:8081/api/shop/1/stock?from=0&quantity=10
Cache-Control: no-cache
Content-Type: application/json
