create table usr (
    Id SERIAL PRIMARY KEY,
    user_name CHARACTER VARYING(255),
     email CHARACTER VARYING(255),
    password CHARACTER VARYING(255),
    status CHARACTER VARYING(100) DEFAULT 'ACTIVE',
    role CHARACTER VARYING(30),
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update TIMESTAMP WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(Id)
);
create table roles (
    Id SERIAL PRIMARY KEY,
    name CHARACTER VARYING(255),
    status CHARACTER VARYING(100) DEFAULT 'ACTIVE',
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update TIMESTAMP WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(Id)
);
create table user_roles (
 user_id INTEGER  REFERENCES usr(Id),
 role_id INTEGER  REFERENCES roles(Id)
);